name: node

on:
  workflow_dispatch: # lets you run a build from the UI
  push:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: node-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_ENV: "production"
  BUILD_PATH: "build"
  PUBLIC_URL: "https://nh-pages.stoneydsp.com/ts-esbuild-react/"
  HOST: "nh-pages.stoneydsp.com"
  PORT: 80
  HTTPS: true
  TSC_COMPILE_ON_ERROR: false
  # fast refresh probably does nothing in prod...
  FAST_REFRESH: true

jobs:

  run:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: Install
      shell: bash
      working-directory: ${{ github.workspace }}
      run: yarn

    - name: Build
      shell: bash
      working-directory: ${{ github.workspace }}
      run: yarn build

    - name: Test
      shell: bash
      working-directory: ${{ github.workspace }}
      run: yarn test

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ts-esbuild-react-${{ matrix.os }}-node-v${{ matrix.node-version }}
        path: '${{ github.workspace }}/${{ env.BUILD_PATH }}'

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ts-esbuild-react-${{ matrix.os }}-node-v${{ matrix.node-version }}
        path: '${{ github.workspace }}/${{ env.BUILD_PATH }}'
        github-token: ${{ env.GITHUB_TOKEN }}
